export const projectsData = [
  {
    id: '5.1',
    title: 'Senior Prozessmanager - Aufbau und Implementierung ITSM-Prozesse',
    client: 'Landesamt für zentrale polizeiliche Dienste (LZPD Duisburg)',
    period: '09.2020 – 05.2024',
    role: 'Senior Prozessmanager, Senior Service Manager, Management Consultant',
    objective: 'Aufbau und Implementierung der IT-Service Management Prozesse (ITSM) auf Basis von ITIL',
    highlights: [
      'Gesamtsteuerung für den Aufbau und Implementierung einer CMDB',
      'Erstellung der Gesamtkonzeption für einen Modularen Aufbau der CMDB',
      'Definition der Basis Infrastruktur und des Configuration Management Systems (CMS)',
      'Moderation von übergreifenden Veranstaltungen und Workshops',
    ],
    technologies: ['ITIL', 'CMDB', 'BMC Remedy', 'BIC Process Design', 'GBTEC BPMN', 'VMware', 'Proxmox', 'Kubernetes'],
  },
  {
    id: '5.2',
    title: 'ITSM Workstream Lead Outsourcing und Senior Business Analyst',
    client: 'LANXESS AG / Bayer AG',
    period: '12.2019 - 08.2020',
    role: 'ITSM Workstream Lead Outsourcing, Senior Business Analyst',
    objective: 'Steuerung der IT Service Management Vertragsabstimmungen für ein IT-Outsourcing',
    highlights: [
      'Erstellung von Templates für Produkte, Services, Service Requests',
      'Service-Katalog Template und Root Cause Analyse (RCA) Template',
      'Erstellung Service LifeCycle',
    ],
    technologies: ['ServiceNow', 'ITIL', 'SLA-Framework'],
  },
  {
    id: '5.3',
    title: 'Senior Business Analyst - Aufbau Providermanagement',
    client: 'Postbank AG / Postbank Systems AG',
    period: '01.01.2017 – 31.03.2019',
    role: 'Senior Business Analyst',
    objective: 'Aufbau Providermanagement in der Plattform SB',
    highlights: [
      'Gesamtsteuerung der IT (Strategische Ziele & Planung, Service-Monitoring & Reporting)',
      'Operative Steuerung (Applikation- & Testmanagement, Rolloutmanagement)',
      'Vertrags- und Risikomanagement',
    ],
    technologies: ['SB-Banking', 'Managed Services'],
  },
  {
    id: '5.4',
    title: 'Senior Business Analyst - Governance- und Vendor-Steuerung',
    client: 'Postbank AG / Postbank Systems AG',
    period: '24.11.2014 – 31.12.2016',
    role: 'Senior Business Analyst',
    objective: 'Aufbau, Dokumentation und Implementierung einer Governance- und Vendor-Steuerung',
    highlights: [
      'Governance-Review-Board in der Plattform SB implementiert',
      'Integration in Service-Review-Meetings',
      'Automatisierter Prozess für Übernahme von SB-Assets in SAP',
    ],
    technologies: ['SAP', 'SB-Banking', 'Governance-Framework'],
  },
  {
    id: '5.5',
    title: 'Senior Testmanager - MaRisk-konformer Testregelprozess',
    client: 'UniCredit Bank AG / HypoVereinsbank',
    period: '07.01.2013 – 14.11.2014',
    role: 'Senior Testmanager',
    objective: 'Erstellung und Implementierung eines MARisk-konformen bankübergreifenden Testregelprozesses',
    highlights: [
      'Planung und Durchführung der Schulungen für das MARisk-konforme Testvorgehen',
      'Erstellung und Implementierung eines Test Governance-Prozesses',
      'Komplette Abnahme durch den Wirtschaftsprüfer der Großbank',
    ],
    technologies: ['HP Quality Center (HP QC)', 'MaRisk', 'BaFin-Vorgaben'],
  },
  {
    id: '5.6',
    title: 'Senior Test- und Release-Manager - Agiles Kernbankensystem',
    client: 'Mercedes-Benz Bank (MB Bank)',
    period: '31.07.2012 – 31.12.2012',
    role: 'Senior Test- und Release-Manager',
    objective: 'Einführung eines zentralen Kernbankensystems (Thaler) mit agiler Vorgehensweise',
    highlights: [
      'Sicherstellung Aufbau der Projektinstanz (KBS) in HP QC',
      'Planung des Übergangs von den Iterationen in die produktiven Release Phasen',
    ],
    technologies: ['HP Quality Center', 'Scrum', 'Lean', 'Kanban', 'Thaler Kernbankensystem'],
  },
  {
    id: '5.7',
    title: 'Teilprojektleitung als Senior Qualitätsmanager im Konsortium',
    client: 'DZ BANK AG',
    period: '01.04.2011 – 27.01.2012',
    role: 'Teilprojektleiter als Senior Qualitätsmanager',
    objective: 'Qualitätsmanagement für IT-Outsourcing-Projekt',
    highlights: [
      'Durchführung von QS-Abnahmeworkshops',
      'Sicherstellung vertragsrelevanter Abnahmen',
    ],
    technologies: ['Managed Services', 'Kernbankensysteme'],
  },
  {
    id: '5.8',
    title: 'Teilprojektleitung als Senior Qualitätsmanager (Stabsstelle - QSV)',
    client: 'Union Investment (UIT)',
    period: '01.01.2010 – 31.03.2011',
    role: 'Teilprojektleitung als Senior Qualitätsmanager',
    objective: 'Definition von Abnahmeprozessen und Qualitätssicherungs-Aktivitäten',
    highlights: [
      'Stabsstelle direkt beim Projektmanagement',
      'Enge Zusammenarbeit mit der Konzernrevision',
    ],
    technologies: ['Outsourcing', 'Providerwechsel'],
  },
  {
    id: '5.9',
    title: 'Teilprojektleitung - Senior Test- und Migrations-Manager',
    client: 'Union Investment (UIT)',
    period: '06.08.2009 – 31.12.2009',
    role: 'Senior Test- & Migrations-Manager',
    objective: 'Aufbau übergreifendes Testmanagement und Migrationsmanagement',
    highlights: [
      'Koordination komplexer Migrationsaktivitäten',
      'Aufbau Migrationsleitstand',
    ],
    technologies: ['Outsourcing', 'Migrationsleitstand'],
  },
  {
    id: '5.10',
    title: 'Senior Release Manager (Lifecycle)',
    client: 'Deutsche Bank AG',
    period: '02.01.2009 – 30.04.2009',
    role: 'Senior Release Manager',
    objective: 'Aufbau eines übergreifenden Release Managements (Lifecycle)',
    highlights: ['Lifecycle-orientiertes Release Management'],
    technologies: ['Release Management'],
  },
  {
    id: '5.11',
    title: 'Senior Projektmanager - Provider Bewertung',
    client: 'Commerzbank AG',
    period: '01.08.2007 – 30.05.2008',
    role: 'Senior Projektmanager',
    objective: 'Projektmanagement für drei Herstellerbewertungsprojekte im SB-Banking',
    highlights: ['Parallele Steuerung von drei Bewertungsprojekten'],
    technologies: ['SB-Banking'],
  },
  {
    id: '5.12',
    title: 'Senior Projektmanager - Bereich IT/Technik',
    client: 'Commerzbank AG',
    period: '09.01.2006 – 31.07.2007',
    role: 'Projektleitung',
    objective: 'Projektmanagement für den gesamten Bereich IT/Technik',
    highlights: ['Übergreifende IT-Kapazitätsplanung'],
    technologies: ['IT-Infrastruktur'],
  },
  {
    id: '5.13',
    title: 'Senior Consultant - Einführung Cash-Recycling-Geräte',
    client: 'Deutsche Bank AG',
    period: '01.05.2003 – 23.11.2005',
    role: 'Senior Consultant',
    objective: 'Einführung von Cash-Recycling-Geräten (SB Banking)',
    highlights: ['Spezialist für SB-Banking Zahlungssysteme'],
    technologies: ['Cash-Recycling', 'SB-Banking'],
  },
  {
    id: '5.14',
    title: 'Senior Consultant - Internet-Geschäftsvorfälle am Kundenterminal',
    client: 'Deutsche Bank AG',
    period: '03.02.2003 – 30.04.2003',
    role: 'Senior Consultant',
    objective: 'Fachkonzept für Internet-Geschäftsvorfälle am Kundenterminal',
    highlights: ['Innovative Lösung für Internet-Banking am Terminal'],
    technologies: ['SB-Banking', 'Internet-Banking'],
  },
  {
    id: '5.15',
    title: 'Projektleitung und Consulting - Outsourcing Betriebsführung',
    client: 'Bankgesellschaft Berlin AG',
    period: '18.10.1999 – 30.06.2000',
    role: 'Projektleitung und Consultant',
    objective: 'Outsourcing für komplette Übernahme der Betriebsführung im SB Banking',
    highlights: ['Komplettes Outsourcing der Betriebsführung'],
    technologies: ['SB-Banking', 'Outsourcing'],
  },
  {
    id: '5.16',
    title: 'Senior Consultant - IT Rollout/Migration',
    client: 'EuroHypo AG',
    period: '05.07.1999 – 30.09.1999',
    role: 'Senior Consultant',
    objective: 'Rollout/Migration von IBM OS/2 auf Windows NT für ca. 600 Clients',
    highlights: ['Migration von 600 Clients', 'Aufbau Call-Center'],
    technologies: ['IBM OS/2', 'Windows NT'],
  },
  {
    id: '5.17',
    title: 'Projektleitung und Consulting - IT-Umzug',
    client: 'Adam Opel AG',
    period: '18.08.1997 – 03.07.1999',
    role: 'Projektleitung und Consultant',
    objective: 'Projektsteuerung für zeitkritischen IT-Umzug und Rollout/Migration',
    highlights: [
      'Zeitkritischer IT-Umzug für 1200 Anwender',
      'Rollout für 6000 Clients',
    ],
    technologies: ['IT-Infrastruktur', 'Migration'],
  },
];

export const referencesData = [
  {
    client: 'Landesamt für zentrale polizeiliche Dienste (LZPD Duisburg)',
    period: '09.2020 – 05.2024',
    role: 'Senior Prozessmanager, Senior Service Manager, Management Consultant',
    focus: 'Aufbau und Implementierung ITSM-Prozesse',
  },
  {
    client: 'LANXESS AG / Bayer AG',
    period: '12.2019 - 08.2020',
    role: 'ITSM Workstream Lead Outsourcing, Senior Business Analyst',
    focus: 'IT-Outsourcing, Provider- & Governance Management',
  },
  {
    client: 'Postbank AG / Postbank Systems AG',
    period: '01.01.2017 – 31.03.2019',
    role: 'Senior Business Analyst',
    focus: 'Aufbau Providermanagement, Betreibermodell Outtasking',
  },
  {
    client: 'Postbank AG / Postbank Systems AG',
    period: '24.11.2014 – 31.12.2016',
    role: 'Senior Business Analyst',
    focus: 'Governance- und Vendor-Steuerung',
  },
  {
    client: 'UniCredit Bank AG / HypoVereinsbank',
    period: '07.01.2013 – 14.11.2014',
    role: 'Senior Testmanager',
    focus: 'MaRisk-konformer Testregelprozess',
  },
  {
    client: 'Mercedes-Benz Bank (MB Bank)',
    period: '31.07.2012 – 31.12.2012',
    role: 'Senior Test- und Release-Manager',
    focus: 'Kernbankensystem mit agiler Vorgehensweise',
  },
  {
    client: 'DZ BANK AG',
    period: '01.04.2011 – 27.01.2012',
    role: 'Teilprojektleiter als Senior Qualitätsmanager',
    focus: 'IT-Outsourcing Managed Services',
  },
  {
    client: 'Union Investment (UIT)',
    period: '01.01.2010 – 31.03.2011',
    role: 'Teilprojektleitung als Senior Qualitätsmanager (Stabsstelle - QSV)',
    focus: 'Qualitätsmanagement, Revisionsabsicherung',
  },
  {
    client: 'Union Investment (UIT)',
    period: '06.08.2009 – 31.12.2009',
    role: 'Senior Test- & Migrations-Manager',
    focus: 'Outsourcing-Providerwechsel',
  },
  {
    client: 'Deutsche Bank AG',
    period: '02.01.2009 – 30.04.2009',
    role: 'Senior Release Manager',
    focus: 'Release Management Lifecycle',
  },
  {
    client: 'Commerzbank AG',
    period: '01.08.2007 – 30.05.2008',
    role: 'Senior Projektmanager',
    focus: 'Provider Bewertung SB-Banking',
  },
  {
    client: 'Commerzbank AG',
    period: '09.01.2006 – 31.07.2007',
    role: 'Projektleitung',
    focus: 'Projektmanagement Bereich IT/Technik',
  },
  {
    client: 'Deutsche Bank AG',
    period: '01.05.2003 – 23.11.2005',
    role: 'Senior Consultant',
    focus: 'Einführung Cash-Recycling-Geräte',
  },
  {
    client: 'Deutsche Bank AG',
    period: '03.02.2003 – 30.04.2003',
    role: 'Senior Consultant',
    focus: 'Internet-Geschäftsvorfälle am Kundenterminal',
  },
  {
    client: 'Dresdner Bank AG',
    period: '02.11.2000 – 16.01.2003',
    role: 'Senior Consultant',
    focus: 'Cash-Recycling-Geräte, Optimierung SB-Betrieb',
  },
  {
    client: 'Bankgesellschaft Berlin AG',
    period: '18.10.1999 – 30.06.2000',
    role: 'Projektleitung und Consultant',
    focus: 'Outsourcing Betriebsführung SB Banking',
  },
  {
    client: 'EuroHypo AG',
    period: '05.07.1999 – 30.09.1999',
    role: 'Senior Consultant',
    focus: 'Rollout/Migration OS/2 auf Windows NT',
  },
  {
    client: 'Adam Opel AG',
    period: '18.08.1997 – 03.07.1999',
    role: 'Projektleitung und Consultant',
    focus: 'IT-Umzug, Rollout/Migration',
  },
];

export const trainingsData = [
  {
    name: 'IHK-zertifizierter Trainer',
    category: 'Zertifizierung',
    description: 'Zertifizierung als Trainer durch die IHK',
  },
  {
    name: 'Professional Scrum Master',
    category: 'Agile',
    description: 'Professionelle Scrum Master Zertifizierung',
  },
  {
    name: 'Professional Scrum Product Owner',
    category: 'Agile',
    description: 'Professionelle Scrum Product Owner Zertifizierung',
  },
  {
    name: 'CITIL Training',
    category: 'ITSM',
    description: 'Integration von ITIL in die Struktur von CMMI',
  },
  {
    name: 'ITIL Foundation Zertifizierung',
    category: 'ITSM',
    description: 'Certificate Foundation in IT Service Management',
  },
  {
    name: 'CMMI Introduction Zertifizierung',
    category: 'Process',
    description: 'Certificate in Capability Maturity Model Integration',
  },
  {
    name: 'Training für Teambuilding und Konflikttraining',
    category: 'Soft Skills',
    description: 'Management Institut Ruhleder',
  },
  {
    name: 'Microsoft Trainer Zertifizierung',
    category: 'IT Training',
    description: 'Zertifikat Microsoft Trainer für FFO (Fit for Office)',
  },
  {
    name: 'HP Mercury Quality Center (HP QC)',
    category: 'Tools',
    description: 'Testmanagement-Tool Trainings im Bankenumfeld',
  },
  {
    name: 'Management Kommunikationstrainings',
    category: 'Soft Skills',
    description: 'Management Institut Ruhleder',
  },
  {
    name: 'Wall Street Institute',
    category: 'Sprachen',
    description: 'Englischausbildung',
  },
  {
    name: 'Berlitz English Level 5',
    category: 'Sprachen',
    description: 'Certificate Berlitz Proficiency Level 5',
  },
  {
    name: 'Inlingua Business English',
    category: 'Sprachen',
    description: 'Training Business englisch',
  },
];
